<a href="https://colab.research.google.com/github/Maruf0275/Machine-Learning-Notes/blob/main/Pandas/Groupby_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

### How to use groupby in pandas

In [3]:
import pandas as pd

data = {
    'City': ['Dhaka', 'Dhaka', 'Chittagong', 'Chittagong'],
    'Salary': [50000, 60000, 40000, 45000]
}

df = pd.DataFrame(data)
df

         City  Salary
0       Dhaka   50000
1       Dhaka   60000
2  Chittagong   40000
3  Chittagong   45000

In [11]:
# groupby
cities = df.groupby('City')

In [6]:
df.groupby('City')['Salary'].mean()

City
Chittagong    42500.0
Dhaka         55000.0
Name: Salary, dtype: float64

In [12]:
len(cities)

2

In [16]:
movies = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/imdb-top-1000.csv')
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [18]:
genres = movies.groupby('Genre')

In [19]:
# aggregation
genres.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [20]:
genres.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [21]:
genres.max()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

In [24]:
genres.agg({'IMDB_Rating':['mean','max']})

          IMDB_Rating
                 mean  max
Genre
Action       7.949419  9.0
Adventure    7.937500  8.6
Animation    7.930488  8.6
Biography    7.938636  8.9
Comedy       7.901290  8.6
Crime        8.016822  9.2
Drama        7.957439  9.3
Family       7.800000  7.8
Fantasy      8.000000  8.1
Film-Noir    7.966667  8.1
Horror       7.909091  8.5
Mystery      7.975000  8.4
Thriller     7.800000  7.8
Western      8.350000  8.8

In [29]:
# find the top 3 genres by total earning
genres['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [34]:
# find the genre with highest avg IMDB rating
genres['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [37]:
# find the director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [40]:
# find number of movies by each actor
movies['Star1'].value_counts()

movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks            12
Robert De Niro       11
Clint Eastwood       10
Al Pacino            10
Leonardo DiCaprio     9
                     ..
Gérard Jugnot         1
Günes Sensoy          1
Haluk Bilginer        1
Harriet Andersson     1
Graham Chapman        1
Name: Series_Title, Length: 660, dtype: int64

In [43]:
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [45]:
# agg method
genres.agg({'IMDB_Rating':['mean','max'],
            'Runtime':['mean'],
            'Gross':['max','min','mean']})

          IMDB_Rating          Runtime        Gross
                 mean  max        mean          max          min          mean
Genre
Action       7.949419  9.0  129.046512  936662225.0       3296.0  1.897224e+08
Adventure    7.937500  8.6  134.111111  874211619.0      61001.0  1.319017e+08
Animation    7.930488  8.6   99.585366  873839108.0     128985.0  1.784326e+08
Biography    7.938636  8.9  136.022727  753585104.0      21877.0  9.404952e+07
Comedy       7.901290  8.6  112.129032  886752933.0       1305.0  1.010572e+08
Crime        8.016822  9.2  126.392523  790482117.0       6013.0  7.899656e+07
Drama        7.957439  9.3  124.737024  924558264.0       3600.0  1.225259e+08
Family       7.800000  7.8  107.500000  435110554.0    4000000.0  2.195553e+08
Fantasy      8.000000  8.1   85.000000  445151978.0  337574718.0  3.913633e+08
Film-Noir    7.966667  8.1  104.000000  123353292.0     449191.0  4.197018e+07
Horror       7.909091  8.5  102.090909  298791505.0      89029.0  9.405902e+07
Mystery      7.975000  8.4  119.083333  474203697.0    1035953.0  1.047014e+08
Thriller     7.800000  7.8  108.000000   17550741.0   17550741.0  1.755074e+07
Western      8.350000  8.8  148.250000   31800000.0    5321508.0  1.455538e+07

In [49]:
# find the highest rated movie in each genre
movies.sort_values('IMDB_Rating', ascending=False).groupby('Genre').head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [56]:
# groupby on multiple cols
duo = movies.groupby(['Director','Star1'])
# size
duo.size()
# get_group
duo.get_group(('Aamir Khan','Amole Gupte'))
duo.get_group(('Christopher Nolan','Christian Bale'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
36,The Prestige,2006,130,Drama,8.5,Christopher Nolan,Christian Bale,1190259,53089891.0,66.0
63,The Dark Knight Rises,2012,164,Action,8.4,Christopher Nolan,Christian Bale,1516346,448139099.0,78.0
155,Batman Begins,2005,140,Action,8.2,Christopher Nolan,Christian Bale,1308302,206852432.0,70.0

In [59]:
# find the most earning actor and director combo
duo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [61]:
# agg on multiple groupby - selecting only numeric columns to avoid TypeError
duo[['IMDB_Rating', 'Gross']].agg(['min', 'max', 'mean'])

                                   IMDB_Rating                  Gross  \
                                           min  max mean          min
Director            Star1
Aamir Khan          Amole Gupte            8.4  8.4  8.4    1223869.0
Aaron Sorkin        Eddie Redmayne         7.8  7.8  7.8  853090410.0
Abdellatif Kechiche Léa Seydoux            7.7  7.7  7.7    2199675.0
Abhishek Chaubey    Shahid Kapoor          7.8  7.8  7.8  218428303.0
Abhishek Kapoor     Amit Sadh              7.7  7.7  7.7    1122527.0
...                                        ...  ...  ...          ...
Zaza Urushadze      Lembit Ulfsak          8.2  8.2  8.2     144501.0
Zoya Akhtar         Hrithik Roshan         8.1  8.1  8.1    3108485.0
                    Vijay Varma            8.0  8.0  8.0    5566534.0
Çagan Irmak         Çetin Tekindor         8.3  8.3  8.3  461855363.0
Ömer Faruk Sorak    Cem Yilmaz             8.0  8.0  8.0  196206077.0


                                            max         mean
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0
...                                         ...          ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0
                    Vijay Varma       5566534.0    5566534.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0

[898 rows x 6 columns]